apiVersion: v1
kind: Service
metadata:
    name: asistenciaplusemailnodejshelloworld
spec:
    type: LoadBalancer
    ports:
    - port: 8080 
    selector:
        app: asistenciaplusemailnodejshelloworld